mappings:
  AkismetConfig: SilverStripe\Akismet\Config\AkismetConfig
  AkismetProcessor: SilverStripe\Akismet\Config\AkismetProcessor
  AkismetService: SilverStripe\Akismet\Service\AkismetService
  AkismetField: SilverStripe\Akismet\AkismetField
  AkismetSpamProtector: SilverStripe\Akismet\AkismetSpamProtector
